### ISSUE TITLE
Can't create account on self hosted server, it always returns "bad login" instead of trying to create account

### ISSUE THREAD

**Issue by alfredbaudisch** [turtl/tracker#320]
I just installed Turtl on a Ubuntu 18.04 server (PgSQL 10 and Node 8) and if I open the API URL in the browser I correctly get: `{"greeting":"Hi."}`. Then in the official Ubuntu and Android clients, when I try to "Join" with a new account, it seems it always try to login instead of creating an account.

This is the config:
```
server:
  host:
  port: 8181

db:
  connstr: 'postgres://~@127.0.0.1:5432/turtl'
  pool: 24

loglevel: 'debug'

app:
  enable_bookmarker_proxy: false
  api_url: 'https://MY_URL_HERE/turtl-api'
  www_url: 'https://MY_URL_HERE/turtl'
```

Apache2 Reverse Proxy:
```
ProxyPreserveHost On
ProxyPass /turtl http://127.0.0.1:8181/ Keepalive=On timeout=1600
ProxyPassReverse /turtl http://127.0.0.1:8181/
ProxyPass /turtl-api http://127.0.0.1:8181/ Keepalive=On timeout=1600
ProxyPassReverse /turtl-api http://127.0.0.1:8181/
```

This is what the server returns:
```
info: Listening for turtls on port 8181...
debug: db: query:  SELECT * FROM users WHERE username = $1 0=email@gmail.com
error: tres.err -- (uid null): bad login: email@gmail.com
info: ::ffff:127.0.0.1 "POST //users" 403 62
```
