### ISSUE TITLE
docker-compose DB now persistent?

### ISSUE THREAD

**Issue by mammique** [turtl/tracker#364]
Hello, the `docker-compose` documentation for the server says: https://github.com/turtl/server#running-the-server-via-docker-compose

> Be aware: after you cancel the docker-compose the data will be lost. For productive usage you may want to store the postgres-data inside a docker volume.

However when I stop and start it again, the data still seems to be there, does it mean that now the DB is persistent? Is it safe to use it like that?

Thank you,

Bests,

Camille.

**Comment by mammique** [comment]
OK, I didn't see that we needed to add a volume to `docker-compose.yml` to make the data persistent:

```
    volumes:
        - /mnt/docker/postgresql/:/var/lib/postgresql/data/pg_data
    environment:
      PGDATA: /var/lib/postgresql/data/pg_data
```
