### ISSUE TITLE
Pic uploading not working as intended

### ISSUE THREAD

**Issue by gozooit** [turtl/tracker#406]
Hi,

I recently built a self-hosted turtl server running on docker behind a nginx proxy. Everything I tested is working fine, but since I tried to use pictures, I got some issues (related to #266).

I was looking for documentation about the config file, bit didn't found anything interesting. I would like to have more informations about the following configuration options :
```
app:
  api_url:'http://127.0.0.1:8181'
  www_url:'https://domain.com'
```
What should I put in those. I guess my current configuration is good since I'm able to access to my server, write standard notes, edit them, etc...

The following one is where I suspect the error comes from
```
uploads:
  local: '/uploads'
  local_proxy: true                   -> As I understood, if local_proxy is enabled there is no need of url:
  #url:'127.0.0.1:8181/uploads'       -> Eventhough, this was the initial configuration (uncommented) and didn't worked
  #url:'https://domain.com/uploads'   -> I tried this setting as well without success
```
The following screeshot is the synchronisation error I got when I tried to upload picture

![sync_waiting](https://user-images.githubusercontent.com/75040809/146175261-b925172f-c8b1-42e9-84bd-a097562ef5be.png)

Translation : 
You got 2 items waiting for synchronisation
file:incoming -> Blocked - This element is blocking the synchronisation. Correct it by unblocking or deleting this item.
file:outgoing -> Blocked by frozen synchronisation

Unlocking the element doesn't work.

This is the related log:

`2021-12-15T11:36:17 - [ERROR][turtl_core::sync] sync::runner() -- files:incoming: main loop: {"message":"http://127.0.0.1:8181/notes/017dba8071ad6c01b922d2022689a737e0913876408d1ca6a1b58f85d79e6a675eb312205a68003a/local-attachment-proxy: an error occurred trying to connect: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée. (os error 10061)","type":"generic"}`

Translation of the non english part : No connection could be established since the target computer refused it.

Furthermore no errors in turtl logs nor in nginx access log..

So.. any hints to get me out of this issue ? 😅
